---
- name: Get elastic ip addresses
  register: eip_info
  amazon.aws.ec2_eip_info:
    region: "{{ region }}"
    filters:
      tag:Environment: "{{ environment_name }}"
      tag:Contact: "{{ my_email_address }}"

- name: Print
  ansible.builtin.debug:
    var: eip_info

- name: Deleteing elastic ip addresses
  loop: "{{ eip_info['addresses'] }}"
  amazon.aws.ec2_eip:
    region: "{{ region }}"
    state: absent
    ip: "{{ item['public_ip'] }}"
