---
- name: Get elastic ip addresses
  register: eip_info
  amazon.aws.ec2_eip_info:
    region: "{{ region }}"

- name: Print
  ansible.builtin.debug:
    var: eip_info

- name: Deleteing elastic ip addresses
  loop: "{{ eip_info['addresses'] }}"
  amazon.aws.ec2_eip:
    region: "{{ region }}"
    state: absent
    ip: "{{ item['public_ip'] }}"
