---
galaxy_info:
  author: Eric C Ames
  description: This role deletes a virtual private cloud (VPC) at amazon

  license: GPL-3.0-only

  min_ansible_version: "2.1"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - amazon
    - deletevpc
dependencies: []
