---
- name: Export workflow job templates
  hosts: localhost
  connection: local

  tasks:

    - name: Check for our mandatory variables
      # You can create a custom credential for the mandatory variables
      changed_when: false
      ansible.builtin.assert:
        that:
          - controller_url is defined
          - controller_user is defined
          - controller_passwd is defined
        fail_msg: "Please make sure your mandatory variables are set"
        success_msg: "All mandatory variables have been set"

    - name: Create a new token using username/password
      changed_when: false
      ansible.controller.token:
        controller_host: https://{{ controller_url }}
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_passwd }}"
        validate_certs: false
        description: Controller Export Token
        scope: write
        state: present

    - name: Export Workflow Job template
      register: my_workflow_info
      changed_when: false
      ansible.controller.export:
        controller_host: https://{{ controller_url }}
        controller_oauthtoken: "{{ controller_token }}"
        workflow_job_templates: "{{ workflow_job_template_name }}"

    - name: Print out my workflow information
      ansible.builtin.debug:
        var: my_workflow_info

    - name: Export workflow job template to a file
      ansible.builtin.copy:
        content: "{{ my_workflow_info | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: "{{ workflow_job_template_name }}_workflow.yaml"
