---
- name: Create containerized Ansible Automation Platform deployment at AWS
  hosts: localhost
  connection: local

  roles:
    - role: vpc_create_aws
    - role: instance_create_aws
    - role: inventory_add_servers

- name: Build out the newly provisioned server
  hosts: control
  become: true

  roles:
    - role: linux_post_install
    - role: linux_account_create
